### ISSUE TITLE
Crash when opening UFO on Mac

### ISSUE THREAD

**Issue by impallari** [trufont/trufont#155]
- Exported UFO from GlyphsApp
- Open TruFont: File → Open → Select the UFO → OK
- Crash

Yosemite 10.10.5

**Comment by adrientetar** [comment]
Can you send this file to me? My email address is written on top of [this document](http://adrientetar.github.io/doc/cv/CV_en.pdf).

**Comment by adrientetar** [comment]
Thank you for sending me the file. The file exported from Glyphs errors because there is a line segment with offCurves in sterling.glif. cc @schriftgestalt

I'll change TruFont such that it prints an error message and recovers instead of crashing when it encounters an invalid file but I don't intend to make any sort of autocorrection inbuilt. 
Also I'll see if I can get either TruFont or the underlying libraries to return an error message that mentions which glyph is concerned (it doesn't right now).

**Comment by schriftgestalt** [comment]
@impallari could you send me the .glyphs file or the .ufo?

**Comment by adrientetar** [comment]
93df2648a9b8369931c28b4ba484c3a095d26a1e should display an error message when an invalid font is opened.

@schriftgestalt Can you keep me updated on the Glyphs issue?

**Comment by schriftgestalt** [comment]
Did the issue happened again? I never got complaints about his before.

**Comment by adrientetar** [comment]
@schriftgestalt Well, in #177 I had a similar issue pointed out. @pathumego Did you export from Glyphs before opening the file in TruFont? If so, was it data drawn in Glyphs or coming from some other source?

**Comment by pathumego** [comment]
It was drawn in FontForge, exported UFO, opend in Glyphs, did some changes, Opend in TruFont. Ill dig up the file tomo and post it, if it helps.
