### ISSUE TITLE
Investigate theming and related APIs

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#156]
Here is a dark-theme: https://gist.github.com/QuantumCD/6245215 
Make sure that all widgets follow QPalette where possible.

**Comment by eliheuer** [comment]
I started looking into theming, and was able to use css to make a simple dark theme for the menu bar: 

![trufontcsstheme](https://user-images.githubusercontent.com/5162664/34442238-d0d4bafe-ec8e-11e7-8682-13aa5f648b2c.png)

It seems like css themes might be the best way to go? IMO, Ideally they would be located in the users .config directory, so the can be easily stored with other dotfiles. 

Something like this:
```
~/.config
        └── trufont
            ├── config
            └── themes
                ├── angry-fruit-salad.qss
                ├── bauhaus-dark.qss
                ├── bauhaus-light.qss
                ├── brockmann.qss
                └── swiss.qss

```

There are lots of widgets with hardcoded colors at the moment, I'm looking into the best way to refactor so that everything is defined in CSS. Any guidance on the best way to do this would be helpful and appreciated! 

This update would go a long way in helping TruFont become more hackable font editor.

**Comment by EwonRael** [comment]
Personally I love the idea of defining everything using CSS. I like this direction
