### ISSUE TITLE
PostScript hinting dialog is missing StdVW and StdHW

### ISSUE THREAD

**Issue by madig** [trufont/trufont#183]
Very important so that the CFF engine can embolden glyphs at smaller pixel sizes to preserve contrast.

**Comment by miguelsousa** [comment]
There's no need to single out these values. What other font editors do at **font-generation time** is:
1. set StdHW as the first value of the StemSnapH list
2. sort the values of the StemSnapH list in increasing order
3. process the V stems similarly

Perhaps the UI should use more general terms (e.g. H/V stems) instead of StemSnapH/V

**Comment by adrientetar** [comment]
```
The Type 1/CFF StdHW and StdVW fields can be derived by taking the first value from the postscriptStemSnapH and postscriptStemSnapV lists.
```

http://unifiedfontobject.org/versions/ufo3/fontinfo.html
