### ISSUE TITLE
Implement interpolation nudge

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#205]
As discussed in #42

**Comment by madig** [comment]
This is implemented already I think, at least for moving points with the mouse while Alt is pressed. Would need to be implemented to work for both mouse and arrow keys.

**Comment by adrientetar** [comment]
7d9ae16cdeaacdf830510c319cd5dd10f6c935bf
17eaea2bbf77e3b4a5482b79c3f87bd3f85b6a38

Cmd+Alt on OSX or Ctrl+Alt on GNU or WinKey+Alt on Windows.

I haven't checked yet if Ctrl+Alt is okay to use on GNU but if not I will change it to use the WinKey too.

**Comment by davelab6** [comment]
Gnu is tricky because there are several common default window manager
hotkey combo that switch desktops / etc with eithet of those 2....

I think the whole hoykey system needs to be redone in such a way that it is
reconfigurable during usage, and has "themes" for locales, and common
preference sets (eg, users of other various apps who prefer things a
certain way)

**Comment by pathumego** [comment]
Yes. But, themes for changing appearance and hotkeys map should be
separate.
