### ISSUE TITLE
ImportError: No module named 'defconQt.controls.glyphAlignmentWidget'

### ISSUE THREAD

**Issue by madig** [trufont/trufont#279]
https://travis-ci.org/trufont/trufont

How about the policy that master (compilation) should never break?

**Comment by adrientetar** [comment]
a2e5e45d35279e29980306db81d0be5e65117f27

> How about the policy that master (compilation) should never break?

I tried putting all my things into PRs at some point but given that I work on many things at once and not everything is in mergeable state it's easier for me to work as I do. I had limited internet access in the last few days so I pushed that commit directly because it fixed a bug that was there before. 
I subsequently fixed the ImportError but had no internet access by then.
