### ISSUE TITLE
License

### ISSUE THREAD

**Issue by raphaelbastide** [trufont/trufont#4]
What is the license of Trufont?

**Comment by anthrotype** [comment]
Since it uses PyQT, it should be GPLv3, unless one pays for commercial license:

https://riverbankcomputing.com/software/pyqt/intro

@adrientetar could you confirm?

**Comment by adrientetar** [comment]
Dual-licensed GPLv3/LGPL 2.1

**Comment by davelab6** [comment]
I discussed this at length with Adrien and he wishes to permit monopoly
extensions

**Comment by moyogo** [comment]
> Dual-licensed GPLv3/LGPL 2.1
Does this mean GPLv3 with PyQt under GPLv3, and LPGL 2.1 with PyQt under Riverbank commercial license?

**Comment by adrientetar** [comment]
> Does this mean GPLv3 with PyQt under GPLv3, and LPGL 2.1 with PyQt under Riverbank commercial license?

Yes.

**Comment by davelab6** [comment]
Checking the licensing information in https://github.com/trufont/trufont/blob/master/COPYRIGHT I realise that its LGPL2.1 and GPLv3 only; why is this not "or any later version"?

**Comment by davelab6** [comment]
> The Qt Company has announced changes to the open source licensing and product structure of the Qt cross-platform application development framework. "New versions of Qt will be licensed under a commercial license, GPLv2, GPLv3, and LGPLv3, but no longer under LGPLv2.1. The updated open source licenses better ensure end user freedom when using open source licensed versions of Qt. LGPLv3 explicitly forbids the distribution of closed embedded devices. Distributing software under these terms includes a patent grant to all receivers of the software. Commercial Qt licensing removes these requirements and includes professional technical support from The Qt Company."

**Comment by adrientetar** [comment]
Get contributors signoff and I'll do the change.

**Comment by davelab6** [comment]
Are you sure that https://github.com/trufont/trufont/graphs/contributors is
the definitive list of contributors, or did you commit patches submitted to
you privately by others?

**Comment by davelab6** [comment]
> the change

Would you prefer 'the change' to be "adding 'or any later version' to the copyright notice" or, upgrading from 2.1 to 3?

**Comment by adrientetar** [comment]
> upgrading from 2.1 to 3?

Yes

> did you commit patches submitted to
you privately by others?

No

**Comment by moyogo** [comment]
LGTM

**Comment by davelab6** [comment]
What about upgrading from 2.1 to 3 *and* adding 'or any later version', so we don't have to deal with this again.

**Comment by adrientetar** [comment]
No, let's stick to 3 for the time being.

**Comment by davelab6** [comment]
@teddywing you don't have an email associated with your account so I'm pinging you here about this issue. 

To summarise: Qt licensing is changing this year for new versions, they'll only be available under GPL v2, v3 and LGPL v3. But TruFont was licensed under LGPL v2.1 only, and GPLv3 only. So we would like to upgrade the licensing of TruFont. Please give you permission on this bug :)

@adrientetar If we don't hear from Teddy soon, the changes contributed may be minor enoug that copyright doesn't apply so we can go ahead. https://github.com/trufont/trufont/commits?author=teddywing

**Comment by adrientetar** [comment]
or any later version is here to ensure compatibility with any GPL software going forward? Hm. I don't particularly like signing-off on something that doesn't yet exist, though.

**Comment by pathumego** [comment]
Ok I agree for LGPLv3 and GPLv3, I would be ok with any later version

**Comment by anthrotype** [comment]
LGTM (FWIW)

**Comment by n7s** [comment]
I don't claim any rights attached to my very minor contribution. But I think going to v3 is good.

**Comment by davelab6** [comment]
> I don't particularly like signing-off on something that doesn't yet exist, though.

Understandable. Basically it is a question of trust in the FSF; I trust the FSF to update the GPL to continue to defend users' freedom without adding restrictions that restrict users, but some businesses don't like it when loopholes in the GPL are closed so they use "Version X only" to be sure to continue abusing loopholes. And paranoid people say "I can't possibly trust the FSF not to turn evil." But it creates a huge paperwork headache when the FSF updates the license and those people or businesses decide they need to upgrade afterall.

**Comment by graphicore** [comment]
I agree with the changes.

> paranoid people say "I can't possibly trust the FSF not to turn evil."

I guess I'm paranoid then. I mean, the Linux Foundation just turned evil. And also there are crazy laws possible in the US, like the Patriot act.

How about: "GPLv3 or later as long as the FSF doesn't go nuts and later versions of the GPL stay in the spirit of the GPLv3"

**Comment by felipesanches** [comment]
I agree to the changes to LGPLv3 and GPLv3 and I already also give my authorization for an eventual upgrade to later versions of the LGPL and GPL licenses in the future.

**Comment by khaledhosny** [comment]
GPLv3 is fine by me, and I’m in favor of or later as well. In the unlikely event that FSF turns evil (is this even technically possible?), Trufont would be the least of my worries

**Comment by teddywing** [comment]
No problems here. All my present and future contributions can be used under the LGPLv3 and GPLv3 or any future versions of those licenses.

**Comment by davelab6** [comment]
Thanks for the quick reply everyone! 

> FSF turns evil (is this even technically possible?

I think if we assume that the FSF is not already evil or so badly co-opted and feeble that it useless, and want it to stay the same or do better, then no. (I know of at least one GNU old timer who sees it in such a negative light ;) 

The GNU project is a dictatorship under RMS and I am not aware of it doing any succession planning for when he passes away, so I am a bit unsure what will happen to GNU when that happens. 

The FSF however has a board of software freedom activists and if any of them pass away I would not expect the organization to change in nature; it is also a 501c3, not a 501c6 like LiFo, so I think its a bit naieve to say that LiFo only just turned evil because it is by definition an industry puppet :) As a 501c3, the FSF has to serve the public good or be shut down. So I think it is not possible. 

However, the future risks of the FSF as a steward of the GPL family of licenses is somewhat secondary to the current crisis of GPL enforcement, where the GPL compliance requests from linux kernel developers to LiFo members are completely ignored and the resulting lawsuit by SFConvervancy has led to many of their corporate donors ceasing to fund them. 

So if a proprietary font editor started to violate the TruFont LGPL intentionally and refused to comply when asked, then currently we would have no recourse to force their compliance as we are entitled to. At the moment the project is relatively small, but as it grows I think making it a member project of the SFConservancy (or SPI or FSF or FSFE or similar) would be valuable.
