### ISSUE TITLE
Unicode value <-> glyph mapping not working in Source Sans Pro master UFOs

### ISSUE THREAD

**Issue by madig** [trufont/trufont#418]
Version: master
1. Open https://github.com/adobe-fonts/source-sans-pro/tree/master/RomanMasters/SourceSansPro_0.ufo in Trufont
2. Open e.g. the metrics window to see mostly placeholder glyphs.

Not sure if this is a problem with Trufont or the master files? Importing the final .otf works as expected.

**Comment by moyogo** [comment]
@madig Try with a UFO that has Unicode values assigned to glyphs, or use escaped glyph names `/H/e/l/l/o`.

**Comment by madig** [comment]
So the problem is the missing mapping? This makes it harder to edit the masters...

**Comment by moyogo** [comment]
I guess we could fallback on glyph names.
If there’s no glyph that matches a character:
- try to use it as a glyph name (for [A-Za-z])
- try to use the character’s AGL glyph name
- try to use the character’s uni glyph name
- fail

**Comment by moyogo** [comment]
@madig in the mean time, you can select the glyphs, then open the Metrics window, the selected glyphs’ names will make up the string.

**Comment by madig** [comment]
Well, what's strange is that some mapping *does* exist, otherwise you wouldn't get the correct character next to the glyph in the overview.

I'd vote for some automatic fallback. Thanks for the workaround though.

**Comment by adrientetar** [comment]
I'm not in favor of doing this; the idea is that most of your glyphs have unicode values then you type things in the glyph view, and unencoded glyphs like ligatures are accessed through the shaping engine. For codepoints that aren't on the keyboard you would either do Ctrl+F and select the glyph by name or paste unicode text.  
Putting this fallback would mean people would start typing /A like it's "A" and/or export fonts without unicodes and complain etc. it just seems confusing, if we have unicodes, to go and operate without them. And I am generally in favor of having one way of doing things, unless otherwise needed.

The issue here is unicodes are left all unassigned in the master files, it's unclear why. @frankrolf any reason for this?

> Well, what's strange is that some mapping does exist, otherwise you wouldn't get the correct character next to the glyph in the overview.

The overview shows the glyph and glyph name, it doesn't use unicode (except to display a drawing over empty glyphs).

**Comment by frankrolf** [comment]
I forgot to respond here – sorry.
The reason for the missing Unicode values in SSP were overcome practices. The final Unicode values are assigned at build time via GlyphOrderAndAliasDB, that’s why they were not stored in the font (I think this practice goes back to FontLab problems … (?))

Anyway, it is safe to expect Unicode values in UFOs today, if you need a shortcut to assigning them, you can always use RoboFab’s `f.autoUnicodes()` function.

**Comment by madig** [comment]
Thanks for the insight :) Do you plan on fixing this? I frequently consult the SSP sources and having it done correctly upstream would be nice.
