### ISSUE TITLE
Is PyQt 5.8 necessary?

### ISSUE THREAD

**Issue by madig** [trufont/trufont#446]
Non-running-release distros ship with slightly older versions. Depending on the newest pulls in an externally compiled version of Qt from PyPi. It works, but doesn't respect the system theming and makes debugging crashes harder... defconQt depends on pyqt >= 5.5, wouldn't it be better to keep to that? People can still install newer versions via pip I guess?

**Comment by anthrotype** [comment]
The minimum installation requirements for TruFont (or any python package) are specified in the setup.py `install_requires` field. For pyqt5 this is currently `"pyqt5>=5.5.0"`.
The `install_requires` field is the one used by pip to resolve a package's dependencies, e.g when one does `pip install trufont`.

The pyqt5 version that's specified in the `requirements.txt` file may be the same or may be more recent than the one in the minimum `install_requires`. However, the requirements.txt file is used by the CI setup to create a virtual environment with exact package versions: i.e. it has `==` rather than `>=`, so that the test results will be replicable and deterministic.

From time to time, i.e. when we import feature that's been added in a more recent version of a dependency, we need to also bump the minimum required version in setup.py's `install_requires`.

@madig Is `pyqt5>=5.5` low enough for you?

**Comment by madig** [comment]
`pyqt5>=5.5` would be enough, yes.

Thanks for the explanation. Okay, so I won't use `requirements.txt` and instead do `pip3 install --upgrade --editable . --user`? Good to know.

**Comment by anthrotype** [comment]
Yeah, you could do that. Mind that --upgrade is greedy by default, i.e. will upgrade all the dependencies of the dependencies etc. even if they are already satisfied based on the (minimum) install_requires. That may or may not be what you want. In general for testing on continuous integration, or for deployment (e.g. when we bundle up the TruFont app) one would ideally pin down all the versions. But for devs' local use what you're suggest may ok.

**Comment by anthrotype** [comment]
`pip install` recently got a new `--upgrade-strategy <upgrade_strategy>` option, which allows you to select between `eager` (the current default) and `only-if-needed`, which I guess is what you are after. See pip's docs for more info.

**Comment by anthrotype** [comment]
FYI, in the yet unreleased pip 10, the default upgrade strategy will be `only-if-needed`.
