### ISSUE TITLE
Script-specific stuff doesn't work with text tool (w/ harfbuzz)

### ISSUE THREAD

**Issue by jbmorizot** [trufont/trufont#490]
RTL scripts don't work with text tool (even with harfbuzz as shape engine). Example : in Arabic, I don't have the sub of init, medi, fina.

**Comment by khaledhosny** [comment]
I was discussing this with @adrientetar the other day. Simply TruFont is not setting the correct script and direction when calling HarfBuzz. The way we use HarfBuzz means we need to allow the user to select them (and the language, too) since automatic detection is not working and will not be reliable anyway.

**Comment by adrientetar** [comment]
@khaledhosny Instead or rewriting guess_segment_properties can we just use hb_buffer_set_unicode_funcs so that we can feed the buffer with proper unicodes during the guess phase?

**Comment by adrientetar** [comment]
Uhm nevermind, that seems more of a unicodedata provider than a mapping. But maybe we could add the actual codepoints into the buffer, guess the properties, then add our offset codepoints?

**Comment by adrientetar** [comment]
Okay so I fixed the properties detection locally and it looks like now, still doesn't ligate it seems:

![image](https://user-images.githubusercontent.com/1250894/31354391-8e714d04-ad36-11e7-98aa-7b01e886475e.png)

also the caret is completely broken with rtl currently.

**Comment by adrientetar** [comment]
70cd0b19cabf5ab19d528db66f53e199d7071804

**Comment by khaledhosny** [comment]
Are you feeding HarfBuzz code points or glyph ids? I think there are two use cases here:
1. User typing regular text and the expectation is that HarfBuzz will do its full magic, in this case we **must** give HarfBuzz the real code points not the glyph ids, otherwise many things that depend on the Unicode character properties (like Arabic shaping, many of the Indic things, etc.) will be broken.
2. User selecting glyphs/typing glyph names, then the expectation here I think is that HarfBuzz’s initial shaping is skipped since the user wants just the glyphs he selected, in this case we give HarfBuzz the glyph ids.
3. A mixture of both; user selecting a glyph then typing text, if we do glyph ids for the first part and code points for the second, Arabic shaping will still be broken between the two, but I guess user will have to enable Arabic shaping features manually here (once we have a UI for feature control).

I think the code is currently always doing 2 which why you are not getting Arabic shaping.

**Comment by adrientetar** [comment]
> but I guess user will have to enable Arabic shaping features manually here

What do you mean here, you can manually enable Arabic shaping on mixed gids/text?

**Comment by khaledhosny** [comment]
Arabic shaping is split between font features and logic in the engine; the font has the features `isol`, `init`, `medi`, `fina` and the engine analyzes the text to decide which feature to be applied to which glyphs. In the mixed case part of the buffer is glyph ids (that are invalid characters as far as HarfBuzz is concerned) and part is text, which will cause the engine to chose the wrong feature for the character at the boundary, so you get the left instead of the right:
![1](https://user-images.githubusercontent.com/93914/31377367-7bac4ea6-adb0-11e7-9e49-84b2464df6b7.png) ![2](https://user-images.githubusercontent.com/93914/31377371-7e643fa0-adb0-11e7-9406-be5183a96c5b.png)
Instead of trying to find a complex solution to fix this automatically, I’m suggesting that the user select the middle glyph and manually enable the `medi` feature.

**Comment by adrientetar** [comment]
I see. So should I go for each input glyph: if has unicode add_codepoint else add_gid ?

Seems like that would do the trick, I mean the reason we added the gid thing in the first place was for unencoded glyph support, right? So in that case unencoded glyphs input manually will remain unshaped while text will be shaped..

**Comment by adrientetar** [comment]
Ah ok that corresponds to 3. in your previous comment, I'll give that a shot.

**Comment by khaledhosny** [comment]
I think using glyph’s unicode should do the trick.

**Comment by adrientetar** [comment]
ff1c1004ecec0263b528aaee47bfc2d1b30401e7
