### ISSUE TITLE
Provide docs

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#71]
We need documentation. Also we need to make sure that defcon docs are accessible. Currently it seems the default doc in defcon only shows out-of-code descriptions and the function signatures, not the comments written inline.

**Comment by davelab6** [comment]
I suggest hosting the documentation with readthedocs, and using their webhooks - http://read-the-docs.readthedocs.org/en/latest/webhooks.html 

Alternatively we can use travis to generate the documentation and push it to the gh-pages branch on each commit, such that https://trufont.github.io/trufont and https://trufont.github.io/defcon and so on provides the docs live on the web.

**Comment by twardoch** [comment]
I'll soon opensource some modules that allow for a Github Wiki -> MkDocs -> ReadTheDocs workflow. We use it for the new docs on http://help.fontlab.com/

**Comment by davelab6** [comment]
@twardoch sounds nice! However, I don't recommend using the github wiki system, I think markdown files within the main git tree is better; because the contributions to the wiki aren't counted, and there is no pull request system there. However, I know Adrien loves a clean git commit history, so maybe he doesn't want docs activity cluttering up the timeline ;p

Can your tools be extended to include the info in the code's docstrings?

**Comment by adrientetar** [comment]
Code docs inline the rest are tutorials on the website.

**Comment by twardoch** [comment]
Actually, for a Python-based app, I'd probably recommend http://sphinx-doc.org/ after all, with sources written in reST. Markdown is good for "narrative" pieces but reST seems much better suited for code-intense docs. And it's fine for "narrative" as well, it's just a bit more complex. ReadTheDocs can consume both Sphinx- and MkDocs-generated documentation. Sphinx is much more powerful and extensive, while MkDocs is really very simple. For FLVI, I'll most likely be using reST+Sphinx for the Python portions and Markdown+MkDocs for the narrative docs. Both systems are Python-based and use Jinja2, so it's possible to achieve visual parity between those parts, but I'm not sure if "my" system would be a good choice for TruFont after all.

**Comment by twardoch** [comment]
Since, in a way, reStructuredText is a "superset" of Markdown ( https://gist.github.com/dupuy/1855764 ), it's also possible to draft or initially write the docs in Markdown, then convert to reStructuredText using Pandoc, and integrate with the code-inline Python stuff (written in reST). Then use Sphinx and host at ReadTheDocs. I myself prefer Markdown for writing, but perhaps I'll switch to reStructuredText at some point, for all authoring, or as an intermediate step.

**Comment by davelab6** [comment]
On 26 October 2015 at 13:03, Adrien Tétar <notifications@github.com> wrote:

> Code docs inline the rest are tutorials on the website
>
The website will be Github Jykll?

**Comment by adrientetar** [comment]
is

**Comment by adrientetar** [comment]
Closing in favor of #520.
