### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by RafalBuchner** [trufont/trufont#775]
haven't seen dev movement on this repo for a while, only some python auto updates. Is the project dead?

**Comment by alerque** [comment]
I'm curious what you would *do* differently based on any possible answers to this question.

**Comment by RafalBuchner** [comment]
As for Trufont itself, I wouldn't _do_ anything differently. I just want to see if I, and many others in the industry, should treat Trufont as a serious application when developing my or mine clients' workflow.

I was very excited when I first saw Trufont. I have found myself using it for educational purposes. I would like to contribute to it from time to time and see that my input is not wasted on something with no future.

**Comment by alerque** [comment]
Part of the reason I asked is because "is this dead, should I consider putting it in my client's workflows" is different from "is this project dead, if I submitted patches would they ever get included". Some FOSS problems have AWOL maintainers that will never move on unless somebody forks them. Others just don't have time or resources or ideas to keep adding, but if somebody came along and contributed they would jump in to review and release.

**Comment by RafalBuchner** [comment]
I agree, this kind of question, specially from the coder is missplaced
